### ISSUE TITLE
Can't install go module.

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar-client-go#112] opened 2019-12-08 02:46 UTC
#### Expected behavior
go get github.com/apache/pulsar-client-go@latest

should download and install the latest commit on the master branch

#### Steps to reproduce

$ go get github.com/apache/pulsar-client-go@latest
go: finding github.com/apache/pulsar-client-go latest
go build github.com/apache/pulsar-client-go: no non-test Go files in /Users/jimlambrt/go/pkg/mod/github.com/apache/pulsar-client-go@v0.0.0-20191205202832-862285fee18a

I think this is happening because you only have one .go file in the parent directory https://github.com/apache/pulsar-client-go  and it's a test file.

#### System configuration
$ go version
go version go1.13.4 darwin/amd64

**Comment by Jim-Lambert-Bose** [comment] 2019-12-08 02:53
Looks like the module is download and "installed" but the go.mod file is not updated to reflect the new version.

**Comment by jiazhai** [comment] 2019-12-09 09:06
Thanks for @Jim-Lambert-Bose your reporting. Seems you get the root cause. Would you like to provide a PR to fix it?

**Comment by reugn** [comment] 2019-12-09 18:42
@Jim-Lambert-Bose why do you need to build it?
And what do you mean by 
> go.mod file is not updated to reflect the new version.

I think this dummy main file is redundant.
Opened a PR #116 to tidy this out a bit.

**Comment by Jim-Lambert-Bose** [comment] 2019-12-09 19:19
I agree, your solution is better and should fix the issue.  `go get` was able to download @latest version of the module, but since the "build" failed (with only test files in the root dir) the go tooling would not update the go.mod file in my project that used the pulsar client... effectively, the module was "installed" but the tooling didn't auto-magically update the go.mod file... this meant I could test locally, but there's no way I'd be able to use the @latest version in my deployments.

**Comment by Jim-Lambert-Bose** [comment] 2019-12-09 19:19
Feel free to close my PR since it's superseded by your PR

**Comment by jiazhai** [comment] 2019-12-11 01:59
cool. Thanks a lot for your contribute

**Comment by jiazhai** [comment] 2019-12-11 02:00
Since The PR is merged. will close this issue.

**Closed by jiazhai** 2019-12-11 02:00 UTC
Labels: help wanted, triage/week-50

**Comment by grtfou** [comment] 2019-12-16 08:01
Install module fail.  
```
$ go get -u github.com/apache/pulsar/pulsar-client-go/pulsar

go: finding github.com/apache/pulsar/pulsar-client-go/pulsar latest
go: finding github.com/apache/pulsar/pulsar-client-go latest
go: finding golang.org/x/crypto latest
go: finding golang.org/x/sys latest
go: finding golang.org/x/tools latest
go: finding gopkg.in/check.v1 latest
go: finding golang.org/x/net latest
go: finding golang.org/x/sync latest
go: finding golang.org/x/xerrors latest

# github.com/apache/pulsar/pulsar-client-go/pulsar
In file included from ../../../pkg/mod/github.com/apache/pulsar/pulsar-client-go@v0.0.0-20191214024039-b52449a6604c/pulsar/c_client.go:24:
./c_go_pulsar.h:22:10: fatal error: 'pulsar/c/client.h' file not found
#include <pulsar/c/client.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```
