### ISSUE TITLE
Data race: type connection_pool.go GetConnection() is not concurrent safe

### ISSUE THREAD

**Issue by Jim-Lambert-Bose** [apache/pulsar-client-go#120] opened 2019-12-11 19:46 UTC
## Expected behavior

Internal `func (p *connectionPool) GetConnection(logicalAddr *url.URL, physicalAddr *url.URL) (Connection, error)`  should be concurrent safe.   It reaches into the connection type and reads attrribs protected by a mutex without locking/unlocking

## Actual behavior

Current implementation allows a race condition since there is no call to lock/unlock the sync.Mutex in the connection object while reading its private attribs

https://github.com/apache/pulsar-client-go/blob/dfc17abd753ac2e488021aede74433e681b5df58/pulsar/internal/connection_pool.go#L56
 
## Steps to reproduce
run some tests using the race detector.

I'll submit a PR for this in a few minutes.

**Comment by wolfstudy** [comment] 2019-12-16 06:14
Thanks @Jim-Lambert-Bose work for this.

I can't reproduce the issue in my local, I will close this issue if you encounter this issue again, please reopen it or please let me know, thanks.

**Closed** 2019-12-16 06:28 UTC
