### ISSUE TITLE
short read when reading frame size

### ISSUE THREAD

**Issue by mileschao** [apache/pulsar-client-go#200] opened 2020-03-19 01:52 UTC
Hi.
While using pulsar client, I got 
```
level=info message "Error reading from connection" error="Short read when reading frame size"
```
Question is:
what does this log mean?
what can I do for it, or, How could I deal with it?

Thx for your help.
@sijie @wolfstudy

**Comment by wolfstudy** [comment] 2020-03-20 09:05
Thanks @mileschao for the feedback, the problem seems to be an error reading the message format.  Can you provide more information?

**Comment by zzzming** [comment] 2020-03-20 21:36
similar to this one https://github.com/apache/pulsar-client-go/issues/145 ?

**Comment by mileschao** [comment] 2020-03-21 06:42
> Thanks @mileschao for the feedback, the problem seems to be an error reading the message format. Can you provide more information?

It is a weird problem.
I create a simple client (with the latest version on master branch), and publish messages continually to the pulsar server for a long time.
sometimes, the `Short read when reading frame size` error level log will appear.

I think it is hard to reproduce.

My real question is:
Is there any way to deal with it?
cause it just break the for loop and log it in the code.
and I can not find any way to deal with this error, for example, reconnect, or recreate.
Thx for your time. :-)

**Comment by mileschao** [comment] 2020-03-21 06:47
> similar to this one #145 ? It's supposed to be fixed. Which commit are the client on @mileschao

Em. 
 It may be a useful hint, but I can not figure it out.

I've got the same error information, but, no pulsar proxy here.

I just create a simple client, and continually publish  messages to the pulsar broker.
Thx for your time. :-)

**Comment by sijie** [comment] 2020-04-09 21:58
@mileschao do you encounter any issue when producing? or is the logging just an info logging?

**Comment by mileschao** [comment] 2020-04-14 01:14
> @mileschao do you encounter any issue when producing? or is the logging just an info logging?

@sijie Thx for your attention.

Yes, I can reproduce it frequently. 
and. the log is: 
```
level=info message "Error reading from connection" error="Short read when reading frame size"
```
The real problem is, there is nothing I can do for this.
custom handler for this problem is wanted. :-)

**Comment by sijie** [comment] 2020-04-14 08:37
@mileschao thank you for your reply. Does it impact your application? Or just an error message?

**Comment by mileschao** [comment] 2020-04-16 14:55
> @mileschao thank you for your reply. Does it impact your application? Or just an error message?

producer will stop send message to pulsar cluster.
and the `for loop` break.
[readSingleCommand](https://github.com/apache/pulsar-client-go/blob/86c3e808d0e6521757a54a6908e24d42fc099734/pulsar/internal/connection_reader.go#L43)

```go
for {
		cmd, headersAndPayload, err := r.readSingleCommand()
		if err != nil {
			r.cnx.log.WithError(err).Info("Error reading from connection")
			r.cnx.TriggerClose()
			break
		}

		// Process
		var payloadLen uint32
		if headersAndPayload != nil {
			payloadLen = headersAndPayload.ReadableBytes()
		}
		r.cnx.log.Debug("Got command! ", cmd, " with payload size: ", payloadLen)
		r.cnx.receivedCommand(cmd, headersAndPayload)
	}
```

**Comment by wolfstudy** [comment] 2020-05-15 03:41
@mileschao The #237 has been merged, and i will close the issue. If you reproduce the problem again, or if there is a new update, please reopen it.

**Closed by wolfstudy** 2020-05-15 03:41 UTC
Labels: triage/week-15

**Comment by mileschao** [comment] 2020-05-26 06:52
```
time="2020-05-25T14:11:45+08:00" level=warning msg="Detected stale connection to broker" local_addr="10.187.98.151:54472" remote_addr="pulsar://10.187.128.67:6650"
time="2020-05-25T14:11:45+08:00" level=warning msg="Detected stale connection to broker" local_addr="10.187.98.151:41310" remote_addr="pulsar://10.187.128.66:6650"
time="2020-05-25T14:11:45+08:00" level=warning msg="Failed to write on connection" error="write tcp 10.187.98.151:54472->10.187.128.67:6650: write: broken pipe" local_addr="10.187.98.151:54472" remote_addr="pulsar://10.187.128.67:6650"
time="2020-05-25T14:11:45+08:00" level=info msg="Error reading from connection" error="Short read when reading frame size: EOF" local_addr="10.187.98.151:54472" remote_addr="pulsar://10.187.128.67:6650"
time="2020-05-25T14:11:45+08:00" level=warning msg="Failed to write on connection" error="write tcp 10.187.98.151:41310->10.187.128.66:6650: write: brokenpipe" local_addr="10.187.98.151:41310" remote_addr="pulsar://10.187.128.66:6650"
```
@wolfstudy
I got log above by [PR](https://github.com/apache/pulsar-client-go/pull/237)
```
Short read when reading frame size: EOF
```
How could I deal with it?

**Comment by jackwang123** [comment] 2021-06-11 02:43
i encounter the same problem, have you resolved this problem?
