### ISSUE TITLE
Pulsar Message Backlog:consumer can't consume messages!!!!

### ISSUE THREAD

**Issue by zxbfeng** [apache/pulsar-client-go#232] opened 2020-04-21 11:42 UTC
pulsar version:2.4.2
The pulsar system version is 2.4.2, The producer sends Messages to pulsar successfully, but the consumers can't consume it. Consumers are servers which have been started a long time ago and still alive. When I restart the consumer server, it can consume the backlog messages. The connection' s  state is "ESTABLISHED" between the consumers and the Pulsar system!

**Comment by sijie** [comment] 2020-04-23 01:52
I think there is a bug in 2.4.2 can potentially cause broker stopping dispatch messages to consumers. Can you try a newer version? Or if you can provide more stats collected by `pulsar-admin topics stats`, that would help us troubleshoot the issue.

**Comment by zxbfeng** [comment] 2020-04-23 02:23
OK. I used the pulsar-admin topic stats, it displays like this the subscriptions of the topic message backlog. I find the error msg in the broker log like this: "&nbsp;

".About at the same time, I found all the topics in this cluster&nbsp; aries the same problems.I use the bookkeeper shell&nbsp; find the bookkeeper doesn't has this ledger Id. So would it the zookeeper has some problems and the meta data is wrong. I use pulsar-admin tool to skip one message(927:16)，the consumer continue to consume. Before I skip message the the subcribtions' internal-stats field:" "waitingReadOp" : false", skip it it displays :'"waitingReadOp" : true,', It seems that the consumer is blocked by the "not&nbsp; found ledgerId error".




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sijie Guo"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 上午9:52
收件人: "apache/pulsar-client-go"<pulsar-client-go@noreply.github.com&gt;; 
抄送: "雨的记忆"<261045585@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [apache/pulsar-client-go] Pulsar Message Backlog:consumer can&#39;t consume messages!!!! (#232)





 
I think there is a bug in 2.4.2 can potentially cause broker stopping dispatch messages to consumers. Can you try a newer version? Or if you can provide more stats collected by pulsar-admin topics stats, that would help us troubleshoot the issue.

**Comment by wolfstudy** [comment] 2020-04-25 13:43
> OK. I used the pulsar-admin topic stats, it displays like this the subscriptions of the topic message backlog. I find the error msg in the broker log like this: "&nbsp; ".About at the same time, I found all the topics in this cluster&nbsp; aries the same problems.I use the bookkeeper shell&nbsp; find the bookkeeper doesn't has this ledger Id. So would it the zookeeper has some problems and the meta data is wrong. I use pulsar-admin tool to skip one message(927:16)，the consumer continue to consume. Before I skip message the the subcribtions' internal-stats field:" "waitingReadOp" : false", skip it it displays :'"waitingReadOp" : true,', It seems that the consumer is blocked by the "not&nbsp; found ledgerId error".
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sijie Guo"<notifications@github.com&gt;; 发送时间: 2020年4月23日(星期四) 上午9:52 收件人: "apache/pulsar-client-go"<pulsar-client-go@noreply.github.com&gt;; 抄送: "雨的记忆"<261045585@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [apache/pulsar-client-go] Pulsar Message Backlog:consumer can&#39;t consume messages!!!! (#232) I think there is a bug in 2.4.2 can potentially cause broker stopping dispatch messages to consumers. Can you try a newer version? Or if you can provide more stats collected by pulsar-admin topics stats, that would help us troubleshoot the issue. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks @zxbfeng feedback, After trying the new version, can this problem be solved?

**Comment by wolfstudy** [comment] 2020-08-24 05:40
This problem is caused by a problem on the broker side. After 2.5.0, the problem has been fixed, so close this issue first. If everyone encounter this problem again, please reopen this issue or let me know, thanks.

**Closed by wolfstudy** 2020-08-24 05:40 UTC
Labels: triage/week-17, type/question
