### ISSUE TITLE
support Cumulative ack

### ISSUE THREAD

**Issue by adaiboy** [apache/pulsar-client-go#183] opened 2020-02-11 16:37 UTC
pulsar-client-go use CommandAck_Individual  now,  and we can subscrib a topic in exclusive, so  add CommandAck_Cumulative is usefull.

and it seems not very difficult, may is it already in your scheduler?

**Comment by merlimat** [comment] 2020-02-11 20:38
The cumulative ack was left out on purpose and the reasoning was (in weighted order):
 * Keep things simple in API
 * Keep things simple in client impl
 * Cumulative ack doesn't provide much more performance/effciency
 * Sequential individual acking will be equivalent

**Comment by adaiboy** [comment] 2020-02-13 08:21
> The cumulative ack was left out on purpose and the reasoning was (in weighted order):
> 
> * Keep things simple in API
> * Keep things simple in client impl
> * Cumulative ack doesn't provide much more performance/effciency
> * Sequential individual acking will be equivalent

i have doubts with the " doesn't provide much more peformance" than individual ack
- Cumulative ack doesn't provide much more performance/effciency
- Sequential individual acking will be equivalent

i set up a test cluster, with a persistent topic , just one subscription with exclusive type,
though some config in broker not be perfect, but i tuned the configure some days according to the source code
and i make a test with the test cluster
<img width="396" alt="截屏2020-02-1316 09 59" src="https://user-images.githubusercontent.com/3397286/74414209-ea798d80-4e7b-11ea-83a9-c1ccaa9432d8.png">

first,  i modified the consumer-series add AckCumulative to compare cumulative ack with individual ack and make a producer send msg with best effort
then,  use  cumulative consumer to consume entry , and cumulative ack when 10000 entries received, the consumer can catch the producer
lastly, clear all. restart the producer, but start a consumer with individual ack
just in the red frame， the consumer is much slower than producer

**Comment by merlimat** [comment] 2021-10-11 17:55
@flowchartsman In your example there would be no need to keep the message ids, you could use a Reader and do SeekByTime(): 

```
// Reset the subscription associated with this consumer to a specific message publish time.
	//
	// Note: this operation can only be done on non-partitioned topics. For these, one can rather perform the seek() on
	// the individual partitions.
	//
	// @param timestamp
	//            the message publish time where to reposition the subscription
	//
	SeekByTime(time time.Time) error

```

**Comment by xiaofan-luan** [comment] 2022-09-21 04:40
Cumulative commit seems to be a reasonable feature.
In our scenario, we use a chan to handle all message. If one ack failed(in current pulsar go client ack didn't throw error, I saw some pr is fixing it), what is the expected behaviour?
Do we need to keep all the messages failed and retry later, that seems to be to much for a user

**Comment by Gleiphir2769** [comment] 2022-12-06 13:24
Hi, @merlimat , I think comulative ack needs to be supported in go client.

> Cumulative ack doesn't provide much more performance/effciency

You are right. cumulative ack does not more performance. But the need to support this feature stems more from simplifying code logic for user.

> In our scenario, we use a chan to handle all message. If one ack failed(in current pulsar go client ack didn't throw error, I saw some pr is fixing it), what is the expected behaviour?
Do we need to keep all the messages failed and retry later, that seems to be to much for a user

As @xiaofan-luan shows, cumulative ack actually provides a way for users to decide when their messages are acknowledged by default. For example, a user need to consume 10000 messages continuously. The user may discard all previous messages because the 8000th message is wrong. In this scenario, if cumulative ack is introduced, the user can call cumulative ack directly with the 8000th message and start to receive new message sequence. Caching message ids here I don't think is a good idea.

If cumulative ack is considered to be introduced, I will implement it. @RobertIndie @nodece Could you give some comments? Thanks.

**Comment by RobertIndie** [comment] 2022-12-07 07:51
Hi @Gleiphir2769 , Thanks for bringing this up. Overall, I'm +1 for implementing this feature.

> But in the go client, only one message will be acknowledged per acknowledgment request. Which means cumulative ack will save the ack rpc times.

Right, supporting the cumulative ack will also improve the performance. But We could also implement the ack group tracker to aggregate serval ack(individual or cumulative) into one RPC. This could improve the performance of the individual ack.

> For example, a user need to consume 10000 messages continuously. The user may discard all previous messages because the 8000th message is wrong. In this scenario, if cumulative ack is introduced, the user can call cumulative ack directly with the 8000th message and start to receive new message sequence. Caching message ids here I don't think is a good idea.

This case makes sense to me.

+1 for implementing this feature.

**Comment by geniusjoe** [comment] 2024-03-04 02:46
> Hi @Gleiphir2769 , Thanks for bringing this up. Overall, I'm +1 for implementing this feature.
> 
> > But in the go client, only one message will be acknowledged per acknowledgment request. Which means cumulative ack will save the ack rpc times.
> 
> Right, supporting the cumulative ack will also improve the performance. But We could also implement the ack group tracker to aggregate serval ack(individual or cumulative) into one RPC. This could improve the performance of the individual ack.
> 
> > For example, a user need to consume 10000 messages continuously. The user may discard all previous messages because the 8000th message is wrong. In this scenario, if cumulative ack is introduced, the user can call cumulative ack directly with the 8000th message and start to receive new message sequence. Caching message ids here I don't think is a good idea.
> 
> This case makes sense to me.
> 
> +1 for implementing this feature.

I think grouping acks feature has been supported in PR(https://github.com/apache/pulsar-client-go/pull/957)

**Comment by RobertIndie** [comment] 2024-03-04 12:11
Closed this as implemented in https://github.com/apache/pulsar-client-go/pull/903

**Closed by RobertIndie** 2024-03-04 12:11 UTC
Labels: triage/week-15
