### ISSUE TITLE
golang adds a batch fetch message API

### ISSUE THREAD

**Issue by wangrenyi** [apache/pulsar-client-go#1201] opened 2024-03-28 10:17 UTC
Consumer<byte[]> consumer = pulsarClient.newConsumer().topic("my-topic").subscriptionName("my-subscription")
				.batchReceivePolicy(BatchReceivePolicy.builder().maxNumMessages(10).maxNumBytes(1024 * 1024)
						.timeout(200, TimeUnit.MILLISECONDS).build())
				.subscribe();

		while (true) {
			Messages<byte[]> messages = consumer.batchReceive();
			for (Message<byte[]> msg : messages) {
				// TODO
			}
			consumer.acknowledge(messages);
		}

When will golang provide a batch fetch message, batch submit message API with the same functionality as the java client

**Comment by RobertIndie** [comment] 2024-04-09 14:25
It's duplicate with https://github.com/apache/pulsar-client-go/issues/840

**Comment by RobertIndie** [comment] 2024-04-09 14:29
This issue appears to be a duplicate of https://github.com/apache/pulsar-client-go/issues/840. To keep our issue tracker clean, we're closing this one. Please follow the original issue for further updates.

**Closed by RobertIndie** 2024-04-09 14:29 UTC
